name: log-hours-project

services:
  app:
    image: ${DOCKER_IMAGE}
    container_name: ${CONTAINER_NAME}
    env_file:
      - .env
    volumes:
      - ./screenshots:/app/screenshots
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - work-logger-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  work-logger-network:
    driver: bridge 